/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_imgui_Imgui */

#ifndef _Included_com_badlogic_gdx_imgui_Imgui
#define _Included_com_badlogic_gdx_imgui_Imgui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_imgui_Imgui
 * Method:    getString
 * Signature: (Ljava/lang/Integer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_badlogic_gdx_imgui_Imgui_getString
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_badlogic_gdx_imgui_Imgui
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_imgui_Imgui_getLong
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
