/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_imgui_ImGui */

#ifndef _Included_com_badlogic_gdx_imgui_ImGui
#define _Included_com_badlogic_gdx_imgui_ImGui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getTexDataAsRGBA32
 * Signature: ()Lcom/badlogic/gdx/imgui/ImGuiTexData;
 */
JNIEXPORT jobject JNICALL Java_com_badlogic_gdx_imgui_ImGui_getTexDataAsRGBA32
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getDeltaTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_imgui_ImGui_getDeltaTime
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setDisplaySize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setDisplaySize
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setDeltaTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setDeltaTime
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    newFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_newFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_render
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    showUserGuide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_showUserGuide
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
