/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_imgui_ImGui */

#ifndef _Included_com_badlogic_gdx_imgui_ImGui
#define _Included_com_badlogic_gdx_imgui_ImGui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getTexDataAsRGBA32
 * Signature: ()Lcom/badlogic/gdx/imgui/ImGuiTexData;
 */
JNIEXPORT jobject JNICALL Java_com_badlogic_gdx_imgui_ImGui_getTexDataAsRGBA32
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setKeyMap
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setKeyMap
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getDeltaTime
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_imgui_ImGui_getDeltaTime
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setDisplaySize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setDisplaySize
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setDeltaTime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setDeltaTime
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setMousePos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setMousePos
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setMouseDown
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setMouseDown
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setKeyDown
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setKeyDown
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setKeyCtrl
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setKeyCtrl
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setKeyShift
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setKeyShift
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setKeyAlt
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setKeyAlt
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    isKeysDown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_gdx_imgui_ImGui_isKeysDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    addInputCharacter
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_addInputCharacter
  (JNIEnv *, jclass, jchar);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    isMouseHoveringAnyWindow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_gdx_imgui_ImGui_isMouseHoveringAnyWindow
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    setMouseWheel
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_setMouseWheel
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    newFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_newFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_render
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    showUserGuide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_showUserGuide
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    showTestWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_showTestWindow
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getDrawListCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_imgui_ImGui_getDrawListCount
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getDrawList
 * Signature: (I)Lcom/badlogic/gdx/imgui/ImGuiDrawList;
 */
JNIEXPORT jobject JNICALL Java_com_badlogic_gdx_imgui_ImGui_getDrawList
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getVertBuffer
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_getVertBuffer
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getIndBuffer
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_imgui_ImGui_getIndBuffer
  (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     com_badlogic_gdx_imgui_ImGui
 * Method:    getTotalVtxCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_imgui_ImGui_getTotalVtxCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
